export const classes = [
  'eRallyH1FwdCaps',
  'eRallyH2FwdCaps',
  'eRallyH2RwdCaps',
  'eRallyH3RwdCaps',
  'eRallyGrpB4wdCaps',
  'eRallyGrpACaps',
  'eRallyR2Caps',
  'eRallyNr4R4Caps',
  'eRallyR5Caps',
  'eRallyRGtCaps',
]

export const countries = [
  'eLngArgentina',
  'eLngAustralia',
  'eLngNewZealand',
  'eLngPoland',
  'eLngSpain',
  'eLngUsa'
]

export const stages = [
  {'country': 'eLngArgentina', 'stage': 'Las Juntas', 'km': 8.25},
  {'country': 'eLngArgentina', 'stage': 'Valle de los puentes', 'km': 7.98},
  {'country': 'eLngArgentina', 'stage': 'Camino de acantilados y rocas', 'km': 5.30},
  {'country': 'eLngArgentina', 'stage': 'San Isidro', 'km': 4.48},
  {'country': 'eLngArgentina', 'stage': 'Miraflores', 'km': 3.35},
  {'country': 'eLngArgentina', 'stage': 'El Rodeo', 'km': 2.84},
  {'country': 'eLngArgentina', 'stage': 'Camino a La Puerta', 'km': 8.25},
  {'country': 'eLngArgentina', 'stage': 'Valle de los puentes a la inversa', 'km': 7.98},
  {'country': 'eLngArgentina', 'stage': 'Camino de acantilados y rocas inverso', 'km': 5.30},
  {'country': 'eLngArgentina', 'stage': 'Camino a Coneta', 'km': 4.48},
  {'country': 'eLngArgentina', 'stage': 'Huillaprima', 'km': 3.35},
  {'country': 'eLngArgentina', 'stage': 'La Merced', 'km': 2.84},
  
  {'country': 'eLngAustralia', 'stage': 'Mount Kaye Pass', 'km': 12.50},
  {'country': 'eLngAustralia', 'stage': 'Chandlers Creek', 'km': 12.34},
  {'country': 'eLngAustralia', 'stage': 'Bondi Forest', 'km': 7.01},
  {'country': 'eLngAustralia', 'stage': 'Rockton Plains', 'km': 6.89},
  {'country': 'eLngAustralia', 'stage': 'Yambulla Mountain Ascent', 'km': 6.64},
  {'country': 'eLngAustralia', 'stage': 'Noorinbee Ridge Ascent', 'km': 5.28},
  {'country': 'eLngAustralia', 'stage': 'Mount Kaye Pass Reverse', 'km': 12.50},
  {'country': 'eLngAustralia', 'stage': 'Chandlers Creek Reverse', 'km': 12.34},
  {'country': 'eLngAustralia', 'stage': 'Taylor Farm Sprint', 'km': 7.01},
  {'country': 'eLngAustralia', 'stage': 'Rockton Plains Reverse', 'km': 6.89},
  {'country': 'eLngAustralia', 'stage': 'Yambulla Mountain Descent', 'km': 6.64},
  {'country': 'eLngAustralia', 'stage': 'Noorinbee Ridge Descent', 'km': 5.28},
  
  {'country': 'eLngNewZealand', 'stage': 'Waimarama Point Forward', 'km': 16.06},
  {'country': 'eLngNewZealand', 'stage': 'Te Awanga Forward', 'km': 11.48},
  {'country': 'eLngNewZealand', 'stage': 'Waimarama Sprint Forward', 'km': 8.81},
  {'country': 'eLngNewZealand', 'stage': 'Elsthorpe Sprint Forward', 'km': 7.32},
  {'country': 'eLngNewZealand', 'stage': 'Ocean Beach Sprint Forward', 'km': 6.61},
  {'country': 'eLngNewZealand', 'stage': 'Te Awanga Sprint Forward', 'km': 4.79},
  {'country': 'eLngNewZealand', 'stage': 'Waimarama Point Reverse', 'km': 16.06},
  {'country': 'eLngNewZealand', 'stage': 'Ocean Beach', 'km': 11.48},
  {'country': 'eLngNewZealand', 'stage': 'Waimarama Sprint Reverse', 'km': 8.81},
  {'country': 'eLngNewZealand', 'stage': 'Elsthorpe Sprint Reverse', 'km': 7.32},
  {'country': 'eLngNewZealand', 'stage': 'Ocean Beach Sprint Reverse', 'km': 6.61},
  {'country': 'eLngNewZealand', 'stage': 'Te Awanga Sprint Reverse', 'km': 4.79},
  
  {'country': 'eLngSpain', 'stage': 'Comienzo De Bellriu', 'km': 14.34},
  {'country': 'eLngSpain', 'stage': 'Centenera', 'km': 10.57},
  {'country': 'eLngSpain', 'stage': 'Ascenso por valle el Gualet', 'km': 7.00},
  {'country': 'eLngSpain', 'stage': '*Viñedos dentro del valle Parra', 'km': 6.81},
  {'country': 'eLngSpain', 'stage': '*Viñedos Dardenyà', 'km': 6.55},
  {'country': 'eLngSpain', 'stage': 'Descenso por carretera', 'km': 4.58},
  {'country': 'eLngSpain', 'stage': 'Final de Bellriu', 'km': 14.34},
  {'country': 'eLngSpain', 'stage': 'Camino a Centenera', 'km': 10.57},
  {'country': 'eLngSpain', 'stage': 'Salida desde Montverd', 'km': 7.00},
  {'country': 'eLngSpain', 'stage': 'Ascenso bosque Montverd', 'km': 6.81},
  {'country': 'eLngSpain', 'stage': '*Viñedos Dardenyà inversa', 'km': 6.55},
  {'country': 'eLngSpain', 'stage': 'Subida por carretera', 'km': 4.58},
  
  {'country': 'eLngUsa', 'stage': 'Beaver Creek Trail Forward', 'km': 12.86},
  {'country': 'eLngUsa', 'stage': 'North Fork Pass', 'km': 12.50},
  {'country': 'eLngUsa', 'stage': 'Hancock Creek Burst', 'km': 6.89},
  {'country': 'eLngUsa', 'stage': 'Fuller Mountain Ascent', 'km': 6.64},
  {'country': 'eLngUsa', 'stage': 'Tolt Valley Sprint Forward', 'km': 6.10},
  {'country': 'eLngUsa', 'stage': 'Hancock Hill Sprint Forward', 'km': 6.01},
  {'country': 'eLngUsa', 'stage': 'Beaver Creek Trail Reverse', 'km': 12.86},
  {'country': 'eLngUsa', 'stage': 'North Fork Pass Reverse', 'km': 12.50},
  {'country': 'eLngUsa', 'stage': 'Fury Lake Depart', 'km': 6.89},
  {'country': 'eLngUsa', 'stage': 'Fuller Mountain Descent', 'km': 6.64},
  {'country': 'eLngUsa', 'stage': 'Tolt Valley Sprint Reverse', 'km': 6.10},
  {'country': 'eLngUsa', 'stage': 'Hancock Hill Sprint Reverse', 'km': 6.01},
  
  {'country': 'eLngPoland', 'stage': '*Zaróbka', 'km': 16.46},
  {'country': 'eLngPoland', 'stage': 'Zienki', 'km': 13.42},
  {'country': 'eLngPoland', 'stage': 'Marynka', 'km': 9.25},
  {'country': 'eLngPoland', 'stage': 'Kopina', 'km': 7.03},
  {'country': 'eLngPoland', 'stage': 'Lejno', 'km': 6.72},
  {'country': 'eLngPoland', 'stage': 'Czarny Las', 'km': 6.62},
  {'country': 'eLngPoland', 'stage': '*Zagórze', 'km': 16.46},
  {'country': 'eLngPoland', 'stage': 'Jezioro Rotcze', 'km': 13.42},
  {'country': 'eLngPoland', 'stage': 'Borysik', 'km': 9.25},
  {'country': 'eLngPoland', 'stage': '*Józefin', 'km': 7.03},
  {'country': 'eLngPoland', 'stage': 'Jagodno', 'km': 6.72},
  {'country': 'eLngPoland', 'stage': 'Jezioro Lukie', 'km': 6.62},
]